### ISSUE TITLE
Hoe snel worden updates aan fiches geregistreerd en weergegeven?

### ISSUE THREAD

**Issue by jelle-archiefpunt** [libis/Archiefpunt#14]
Als ik een fiche aanmaak of update, hoe snel is de aanpassing dan gemaakt in de databank? En hoe snel is dit fiche dan geupdated en vindbaar in de zoekfunctie?

**Comment by mehmetc** [comment]
De indexer loopt om de 6 uur. Dus max. 6uur. Kan ook near real time maar dan is het een enhancement.
